
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.Point2D;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author timca
 */
public class VisualizationWindow extends javax.swing.JPanel {

    private ArrayList<PointWithColor> points = new ArrayList<PointWithColor>();
    
    
    
    public VisualizationWindow() {
        initComponents();
    }
    
    public void addPoint(Point2D.Double point,Color color)
    {
       points.add(new PointWithColor(point,color));
    }
    
    public void removeAllPoints()
    {
        points = new ArrayList<PointWithColor>();
    }

    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        g.setColor(new Color(0, 128, 0));
        g.fillRect(0, 0, 460, 300);
        
        g.setColor(Color.white);
        //g.drawLine(230, 0, 230, 300);

        // Yard Lines:
        g.drawLine(0, 150, 460, 150);
        g.drawLine(0, 50, 460, 50);
        g.drawLine(0, 250, 460, 250);

        // Hash Marks
        g.drawLine(0, 100, 50, 100);
        g.drawLine(0, 200, 50, 200);

        g.drawLine(410, 100, 460, 100);
        g.drawLine(410, 200, 460, 200);

        g.setColor(new Color(93, 21, 0));
        g.fillOval(230 - 4, 150 - 8, 8, 16);
        
        g.setColor(Color.blue);
        for (PointWithColor point : points)
        {
            g.setColor(point.color);
            g.fillOval((int)point.point.x*10+230-5, (int)point.point.y*10+150-5, 10, 10);
        }


    }
    private class PointWithColor
    {
        public Point2D.Double point;
        public Color color;
        public PointWithColor(Point2D.Double point, Color color)
        {
            this.color=color;
            this.point=point;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
