
import java.awt.Color;
import java.awt.Graphics;
import java.awt.geom.Point2D;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author timca
 */
public class VisualizationWindow extends javax.swing.JPanel {

    private ArrayList<Point2D.Double> defensePoints = new ArrayList<Point2D.Double>();
    private ArrayList<Point2D.Double> offensePoints = new ArrayList<Point2D.Double>();
    
    
    public VisualizationWindow() {
        initComponents();
    }
    
    public void addOffensePoint(Point2D.Double point)
    {
        offensePoints.add(point);
    }
    
    public void addDefensePoint(Point2D.Double point)
    {
        defensePoints.add(point);
    }

    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.setColor(Color.black);
        g.drawLine(0, 150, 460, 150);
        g.drawLine(230, 0, 230, 300);
        g.setColor(Color.blue);
        for (Point2D.Double point : offensePoints)
        {
            g.drawOval((int)point.x*10+230, (int)point.y*10+150, 5, 5);
        }
        g.setColor(Color.red);
        for (Point2D.Double point : defensePoints)
        {
            g.drawOval((int)point.x*10+230, (int)point.y*10+150, 5, 5);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
